#!/bin/sh
export USER_HOME=/home/asayankin
export OS_IMAGE_DIR=$USER_HOME/os-images
export OS_IMAGE_FORMAT=qcow2
export OS_IMAGE_SIZE=30 #GB
export OS_IMAGE_ROOT_PASSWD=Al3ks3y7!
export OS_IMAGE_VIRT_CPU=3
export OS_IMAGE_MEMORY=8192 #MB
export OS_TYPE='Ubuntu14.04'
export MAPR_VERSION='4.0.2'
export LETS_ROCK_N_ROLL=1
export HBASE_VERSION='0.98.4'
export OS_IMAGE_CLUSTER_NAME=mrv2.mapr.cluster
export SSH_ID_RSA_PUB=$USER_HOME/.ssh/id_rsa.pub
export RUN_CONFIGURE_SH_AFTER_INSTALL=1
export CLUSTER_SECURE=none # Possible values: none|mapr|kerberos
export KRB_DEFAULT_REALM=CYBERVISIONTECH.COM.UA
export KRB_DATABASE_PASSWD=Al3ks3y7!
export KRB_ADMIN_USER_PASSWD=Al3ks3y7!
export KRB_MAPR_USER_PASSWD=Al3ks3y7!